baseURL = ""
languageCode = "en-us"
title = "Course Template"
theme = "blnk"
[outputFormats]
  [outputFormats.slide]
    mediaType = "text/html"
    name = "slide"
    path = "slides"
    isHTML = "true"
[outputs]
  home = ["HTML", "slide"]
  page = ["HTML", "slide"]
  post = ["HTML", "slide"]
[params]
  author = "Simon Borer"
  description = "Humber HTTP* Course Template"
  mainSections = ["posts"]
[markup.goldmark.renderer]
  unsafe= true